### ISSUE TITLE
Since the speed up udpate the modwtmra gives only zeroes

### ISSUE THREAD

**Issue by Espritdelescalier** [pistonly/modwtpy#4]
As said in the title, tried with my own code and the sample code.

**Comment by Espritdelescalier** [comment]
The .astype(int) in the circular_convolve_mra function is the problem for me so I changed it to .astype(float). I don't know if it justifies a pull request.

**Comment by dubmarm** [comment]
That solved my issue. Thanks!

**Comment by Espritdelescalier** [comment]
If you're curious, I ended up using pywavelets to do the same thing but quicker.
Using mra with swt and a few tweaks you get the same results in about half the time on my machine. The only catch is that you need a sequence length that is a multiple of 2^(level of decomp you want), if you want a 10th level decomp (to get 11 sub frequencies) you need a sequence length that can be divided by two 10 times. So a bit of coding to pad the sequence to the required length and presto! Same but better (with an actively maintained library). To mitigate boundary effects you can try multiple padding schemes (I used reflection but that's just me). Anyway glad I could help.

**Comment by pistonly** [comment]
updated
